image_width: 640
image_height: 480
camera_name: usb_cam
camera_matrix:
  rows: 3
  cols: 3
  data: [513.82239,   0.     , 314.75298,
         0.     , 542.85077, 115.2368 ,
         0.     ,   0.     ,   1.     ]
camera_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [-0.062149, 0.016372, -0.059706, -0.000666, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [404.25592,   0.     , 317.83983,   0.     ,
         0.     , 457.87326, 226.34608,   0.     ,
         0.     ,   0.     ,   1.     ,   0.     ]
