#!/bin/bash
# Waypoint Planner Quick Test Commands

echo "🛰️ Wildlife Patrol Waypoint Planner - Quick Test Commands"
echo "=========================================================="
echo ""

echo "📋 准备工作:"
echo "   cd ~/vision_ws"
echo "   source devel/setup.bash"
echo ""

echo "🚀 基本测试:"
echo "   # 使用默认参数（起点A1B1，禁飞区A3B3 A4B3 A5B3）"
echo "   roslaunch waypoint_planner plan.launch"
echo ""

echo "🎯 自定义测试:"
echo "   # 自定义起点和禁飞区"
echo "   roslaunch waypoint_planner plan.launch start_point:=\"A1B1\" no_fly_zones:=\"A5B5 A6B5 A7B5\""
echo ""
echo "   # 复杂禁飞区测试"
echo "   roslaunch waypoint_planner plan.launch start_point:=\"A9B9\" no_fly_zones:=\"A2B2 A2B3 A3B2 A3B3 A7B7 A8B7\""
echo ""

echo "📡 查看结果:"
echo "   # 查看航点序列"
echo "   rostopic echo /waypoints"
echo ""
echo "   # 查看话题信息"
echo "   rostopic info /waypoints"
echo "   rostopic hz /waypoints"
echo ""

echo "🧪 运行测试脚本:"
echo "   # 在另一个终端运行"
echo "   rosrun waypoint_planner test_waypoint_planner.py"
echo ""

echo "🎨 可视化:"
echo "   # RViz已包含在launch文件中，或手动启动:"
echo "   rviz -d \$(rospack find waypoint_planner)/config/waypoint_planner.rviz"
echo ""

echo "🔧 调试命令:"
echo "   # 查看节点状态"
echo "   rosnode list | grep waypoint"
echo "   rosnode info /waypoint_planner"
echo ""
echo "   # 查看消息类型"
echo "   rosmsg show waypoint_planner/PointArray"
echo ""

echo "📊 示例输出解读:"
echo "   航点格式: A{行号}B{列号} -> (x, y, z)"
echo "   例如: A9B1 -> (0.0, 8.0, 1.2)"
echo "   坐标说明: 网格(1,1)对应世界(0,0)"
echo "   注意: 这是2D规划，所有航点保持相同的固定高度1.2m"
echo ""

echo "🎨 启用可视化:"
echo "   # 启动时开启RViz"
echo "   roslaunch waypoint_planner plan.launch rviz:=true"
echo ""
echo "   # 手动启动RViz"
echo "   rviz -d \$(rospack find waypoint_planner)/config/waypoint_planner.rviz"
echo ""

echo "⚠️  注意事项:"
echo "   - 起点不能在禁飞区内"
echo "   - 坐标范围: A1B1 到 A9B9 (9x9网格)"
echo "   - 路径会自动返回起点形成闭环"
echo "   - 使用A*算法避开禁飞区"
echo "   - 固定飞行高度，只进行2D路径规划"
